lobbyLocation: world,-275.5,236.0,61.5,-180.0,0.0
arenaLocation: world,-275.5,222.3543493612665,61.5,-180.0,0.0
gameStartLocation: world,-275.5,222.3543493612665,61.5,-180.0,0.0
alwaysTeleportToLobby: true
build: false
dropping: false
drowning: false
explosions: false
hunger: false
itemDamage: false
noFall: true
pvp: true
regen: true
launchPads: true
deathMatch: true
launchPadStrength: 3.3
knockbackStrength: 2
timeBeforeDeathMatch: 120
playersForDeathMatch: 4
invincibility: true
autoRespawn: true
mode: true
pearlDeaths: false
suffocationDamage: false